const data = {
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      cetegory: 'shirt',
      image: '/images/p1.jpg',
      category: 'Shirts',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Slim shirt',
      slug: 'adidas-slim-shirt',
      cetegory: 'shirt',
      image: '/images/p2.jpg',
      category: 'Shirts',
      price: 25,
      countInStock: 20,
      brand: 'adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'Nike-slim-Pant',
      cetegory: 'shirt',
      image: '/images/p3.jpg',
      price: 120,
      category: 'Pants',
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality pant',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      cetegory: 'shirt',
      image: '/images/p4.jpg',
      category: 'Pants',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pant',
    },
  ],
};

export default data;
